apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: asdasd
  description: asdasdasd
  annotations: 
    github.com/project-slug: blamdemo/asdoineng
    backstage.io/github-actions-id: blamdemo/asdoineng
spec:
  type: service
  lifecycle: experimental
  owner: guest
